name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  cabal-version: '3.10.1.0'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ghc: ['9.0.2', '9.2.7', '9.4.4', '9.6.1']
    name: Build on GHC ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ghcup
            ~/.cabal
            dist-newstyle
            test-bin
          key: ${{ runner.os }}-${{ matrix.ghc }}-env
      
      - name: Setup Haskell
        run: |
          ghcup install ghc ${{ matrix.ghc }} --set
          ghcup install cabal ${{ env.cabal-version }} --set
      
      - name: Install dependencies
        run: |
          cabal update
          cabal build --only-dependencies --enable-tests --enable-benchmarks
      - name: Build
        run: cabal v2-build --write-ghc-environment-files=always --enable-tests --enable-benchmarks all
      
      - name: Run tests
        run: cabal v2-test --write-ghc-environment-files=always matchable:matchable-test matchable-th:matchable-th-test
      
      - name: Run doctest
        run: |
          cabal install --overwrite-policy=always --install-method=copy --installdir=./test-bin doctest
          chmod u+x ./test-bin/doctest
          cabal repl --with-ghc=./test-bin/doctest
