name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        ghc: ['8.2.2', '8.4.4', '8.6.5', '8.8.3', '8.10.2']
        cabal: ['3.2.0.0']
    name: Haskell GHC ${{ matrix.ghc }} sample
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Cache(compilers)
        uses: actions/cache@v1
        env:
          cache-name: cache-env2
        with:
          path: |
            /opt/ghc
            /opt/cabal
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ env.cache-name }}
      
      - name: Setup Haskell
        uses: actions/setup-haskell@v1.1.2
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      
      - name: Cache(Project)
        uses: actions/cache@v1
        env:
          cache-name: cache-cabal2
        with:
          path: |
            dist-newstyle
            ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ env.cache-name }}-${{ hashFiles('**/*.cabal', 'cabal.project') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-${{ env.cache-name }}-${{ hashFiles('**/*.cabal', 'cabal.project') }}
            ${{ runner.os }}-${{ matrix.ghc }}-${{ env.cache-name }}-
      
      - name: Install dependencies
        run: |
          cabal update
          cabal build --only-dependencies --enable-tests --enable-benchmarks
      - name: Build
        run: cabal build --enable-tests --enable-benchmarks all
      - name: Run tests
        run: cabal test all
