name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ghc: ['8.8.4', '8.10.7', '9.0.2', '9.2.4', '9.4.2']
    name: Build on GHC ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ghcup
            ~/.cabal
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-env
      
      - name: Setup Haskell
        run: |
          ghcup install ghc ${{ matrix.ghc }}
          ghcup set ghc ${{ matrix.ghc }}
          ghcup install cabal
      
      - name: Install dependencies
        run: |
          cabal update
          cabal build --only-dependencies --enable-tests --enable-benchmarks
      - name: Build
        run: cabal v2-build --write-ghc-environment-files=always --enable-tests --enable-benchmarks all
  
  test:
    strategy:
      fail-fast: false
      matrix:
        ghc: ['8.8.4', '8.10.7', '9.0.2', '9.2.4']
    needs: build
    name: Test on GHC ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Cache
        id: restore-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ghcup
            ~/.cabal
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-env
      
      - name: 'Guard(cache was restored)'
        if: ${{ !(steps.restore-cache.outputs.cache-hit) }}
        run: exit 1
      
      - name: Setup Haskell
        run: |
          ghcup install ghc ${{ matrix.ghc }}
          ghcup set ghc ${{ matrix.ghc }}
          ghcup install cabal
      
      - name: Run tests
        run: cabal v2-test --write-ghc-environment-files=always matchable:matchable-test matchable-th:matchable-th-test
      
      - name: Run doctest
        run: |
          cabal install --overwrite-policy=always --install-method=copy --installdir=./test-bin doctest
          chmod u+x ./test-bin/doctest
          cabal repl --with-ghc=./test-bin/doctest
